'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class WebForm1

    '''<summary>
    '''DS_Citas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DS_Citas As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''DS_CitasEmpleado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DS_CitasEmpleado As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''DS_CitasLocal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DS_CitasLocal As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''DS_Usuario control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DS_Usuario As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''DS_Empleado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DS_Empleado As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''DS_Local control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DS_Local As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''lbUsuario control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbUsuario As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbEmpleadoCita control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbEmpleadoCita As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbLocalCita control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbLocalCita As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LbEstatusCita control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LbEstatusCita As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbRol control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbRol As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''divCitas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divCitas As Global.System.Web.UI.HtmlControls.HtmlGenericControl
End Class
